-- used
CREATE TRIGGER AFTER_SLS_BOOKING_DETAILS_INSERT
  AFTER INSERT
  ON SLS_BOOKING_DETAILS FOR EACH ROW
BEGIN

    DECLARE VAR_TOTAL_ITEM_QTY int default 0; 
    DECLARE VAR_SUBTOTAL_PRICE FLOAT default 0;
    DECLARE VAR_SUBTOTAL_PRICE_DECIMAL FLOAT default 0;

    DECLARE VAR_TOTAL_PRICE float default 0;
    DECLARE VAR_SUBTOTAL_PRICE float default 0;
    DECLARE VAR_POSTAGE_COST FLOAT default 0;
    DECLARE VAR_DISCOUNT FLOAT default 0;
    DECLARE VAR_COUPON_DISCOUNT FLOAT default 0;
    DECLARE VAR_TOTAL_PRICE_DECIMAL FLOAT default 0;
    DECLARE VAR_SUBTOTAL_PRICE_DECIMAL FLOAT default 0;

    
    SELECT COUNT(*) AS TOTAL_QTY,SUM(LINE_PRICE) INTO VAR_TOTAL_ITEM_QTY,VAR_SUBTOTAL_PRICE
    FROM SLS_BOOKING_DETAILS
    WHERE F_BOOKING_NO = NEW.F_BOOKING_NO;
    
    SELECT (VAR_SUBTOTAL_PRICE % 1) INTO VAR_SUBTOTAL_PRICE_DECIMAL;
    IF VAR_SUBTOTAL_PRICE_DECIMAL < .5 THEN
       SELECT FLOOR(VAR_SUBTOTAL_PRICE) INTO VAR_SUBTOTAL_PRICE;
    ELSE
       SELECT CEILING(VAR_SUBTOTAL_PRICE) INTO VAR_SUBTOTAL_PRICE;
    END IF;
                                       
    UPDATE SLS_BOOKING SET TOTAL_ITEM_QTY = VAR_TOTAL_ITEM_QTY,SUB_TOTAL = VAR_SUBTOTAL_PRICE WHERE PK_NO = NEW.F_BOOKING_NO;
    
END
/
