CREATE TRIGGER AFTER_SLS_BOOKING_DETAILS_DELETE
  AFTER DELETE
  ON SLS_BOOKING_DETAILS FOR EACH ROW
BEGIN

    declare VAR_FREIGHT_COST FLOAT default 0;
    declare VAR_POSTAGE_COST FLOAT default 0;
    declare VAR_PRICE FLOAT default 0;
    declare VAR_TOTAL_FREIGHT_POSTAGE FLOAT default 0;
    declare VAR_TOTAL_ITEM_QTY INT default 0;
    declare VAR_TOTAL_PRICE float default 0;
    declare VAR_F_BRAND INT default 0;
    declare VAR_BRAND_NAME varchar(50) default null;
    declare VAR_F_MODEL INT default 0;
    declare VAR_MODEL_NAME varchar(50) default NULL;
    declare VAR_F_PRD_CATEGORY_ID INT default 0;
    declare VAR_PRD_CATEGORY_NAME varchar(50) default NULL;
    declare VAR_F_PRD_SUB_CATEGORY_ID INT default 0;
    declare VAR_PRD_SUB_CATEGORY_NAME varchar(50) default null;
    declare VAR_F_PRD_VARIANT_NO INT default 0;
    DECLARE VAR_PENALTY_FEE FLOAT default 0;


    SELECT PENALTY_FEE INTO VAR_PENALTY_FEE
    FROM SLS_BOOKING
    WHERE PK_NO = OLD.F_BOOKING_NO;

    SELECT COUNT(*) AS TOTAL_QTY, SUM(LINE_PRICE) INTO VAR_TOTAL_ITEM_QTY, VAR_TOTAL_PRICE
    FROM SLS_BOOKING_DETAILS
    WHERE F_BOOKING_NO = OLD.F_BOOKING_NO;

    SELECT F_PRD_VARIANT_NO INTO VAR_F_PRD_VARIANT_NO FROM INV_STOCK WHERE PK_NO = OLD.F_INV_STOCK_NO;

    SELECT PRD_MASTER_SETUP.F_BRAND
    , PRD_MASTER_SETUP.BRAND_NAME
    , PRD_MASTER_SETUP.F_MODEL
    , PRD_MASTER_SETUP.MODEL_NAME
    , PRD_MASTER_SETUP.F_PRD_CATEGORY_ID
    , PRD_CATEGORY.`NAME` AS PRD_CATEGORY_NAME
    , PRD_MASTER_SETUP.F_PRD_SUB_CATEGORY_ID
    , PRD_SUB_CATEGORY.`NAME` AS  PRD_SUB_CATEGORY_NAME
    INTO VAR_F_BRAND
    , VAR_BRAND_NAME
    , VAR_F_MODEL
    , VAR_MODEL_NAME
    , VAR_F_PRD_CATEGORY_ID
    , VAR_PRD_CATEGORY_NAME
    , VAR_F_PRD_SUB_CATEGORY_ID
    , VAR_PRD_SUB_CATEGORY_NAME
    FROM PRD_MASTER_SETUP
    JOIN PRD_CATEGORY ON PRD_CATEGORY.PK_NO = PRD_MASTER_SETUP.F_PRD_CATEGORY_ID
    JOIN PRD_SUB_CATEGORY ON PRD_SUB_CATEGORY.PK_NO = PRD_MASTER_SETUP.F_PRD_SUB_CATEGORY_ID
    WHERE PRD_MASTER_SETUP.PK_NO = (SELECT F_PRD_MASTER_SETUP_NO FROM PRD_VARIANT_SETUP WHERE PK_NO = VAR_F_PRD_VARIANT_NO);


    IF OLD.CURRENT_IS_FREIGHT = 1 THEN
        SET VAR_FREIGHT_COST = OLD.CURRENT_AIR_FREIGHT;
    ELSE
        SET VAR_FREIGHT_COST = OLD.CURRENT_SEA_FREIGHT;
    END IF;

    IF OLD.CURRENT_IS_SM = 1 THEN
        SET VAR_POSTAGE_COST = OLD.CURRENT_SM_COST;
    ELSE
        SET VAR_POSTAGE_COST = OLD.CURRENT_SS_COST;
    END IF;

    IF OLD.CURRENT_IS_REGULAR = 1 THEN
        SET VAR_PRICE = OLD.CURRENT_REGULAR_PRICE;
    ELSE
        SET VAR_PRICE = OLD.CURRENT_INSTALLMENT_PRICE;
    END IF;

    SET VAR_TOTAL_FREIGHT_POSTAGE = VAR_FREIGHT_COST + VAR_POSTAGE_COST + VAR_PRICE;
    SET VAR_TOTAL_PRICE = VAR_TOTAL_PRICE + VAR_PENALTY_FEE;

    UPDATE SLS_BOOKING
    SET
    FREIGHT_COST = FREIGHT_COST - VAR_FREIGHT_COST
    ,POSTAGE_COST = POSTAGE_COST - VAR_POSTAGE_COST
    ,TOTAL_ITEM_QTY = VAR_TOTAL_ITEM_QTY
    ,TOTAL_PRICE = VAR_TOTAL_PRICE
    WHERE PK_NO = OLD.F_BOOKING_NO;

    UPDATE INV_STOCK
            SET F_BRAND_NO = VAR_F_BRAND
            , BRAND_NAME = VAR_BRAND_NAME
            , F_MODEL_NO = VAR_F_MODEL
            , MODEL_NAME = VAR_MODEL_NAME
            , F_CATEGORY_NO = VAR_F_PRD_CATEGORY_ID
            , CATEGORY_NAME =  VAR_PRD_CATEGORY_NAME
            , F_SUB_CATEGORY_NO = VAR_F_PRD_SUB_CATEGORY_ID
            , SUB_CATEGORY_NAME = VAR_PRD_SUB_CATEGORY_NAME

            WHERE PK_NO = OLD.F_INV_STOCK_NO AND F_BOOKING_NO IS NULL;

END
/
