CREATE TRIGGER BEFORE_SLS_BOOKING_DETAILS_INSERT
  BEFORE INSERT
  ON SLS_BOOKING_DETAILS FOR EACH ROW
BEGIN
    declare VAR_SS_COST FLOAT default 0;
    declare VAR_SM_COST FLOAT default 0;
    declare VAR_AIR_FREIGHT FLOAT default 0;
    declare VAR_SEA_FREIGHT FLOAT default 0;
    declare VAR_REGULAR FLOAT default 0;
    declare VAR_INSTALLMENT FLOAT default 0;
    declare VAR_IS_REGULAR INT default 0;
    declare VAR_UNIT_PRICE FLOAT default 0;
    declare VAR_SINGLE_COMISSION FLOAT default 0;
    declare VAR_TOTAL_COMISSION FLOAT default 0;
    DECLARE VAR_TOTAL_LINE_VALUE FLOAT default 0;
    declare VAR_F_INV_WAREHOUSE_NO int(1) default 0;
    declare VAR_F_BOX_NO int(11) default 0;
    declare VAR_F_SHIPPMENT_NO int(11) default 0;
    
    SELECT
        SS_COST,SM_COST
        ,AIR_FREIGHT_COST
        ,SEA_FREIGHT_COST
        ,REGULAR_PRICE
        ,INSTALLMENT_PRICE  
        ,F_SHIPPMENT_NO 
        ,F_INV_WAREHOUSE_NO   
        ,F_BOX_NO
        INTO
        VAR_SS_COST
        ,VAR_SM_COST
        ,VAR_AIR_FREIGHT
        ,VAR_SEA_FREIGHT
        ,VAR_REGULAR
        ,VAR_INSTALLMENT 
        ,VAR_F_SHIPPMENT_NO
        ,VAR_F_INV_WAREHOUSE_NO
        ,VAR_F_BOX_NO
    FROM INV_STOCK
    WHERE INV_STOCK.PK_NO = NEW.F_INV_STOCK_NO;

    SET NEW.SS_COST                     = VAR_SS_COST;
    SET NEW.SM_COST                     = VAR_SM_COST;
    SET NEW.AIR_FREIGHT                 = VAR_AIR_FREIGHT;
    SET NEW.SEA_FREIGHT                 = VAR_SEA_FREIGHT;
    SET NEW.REGULAR_PRICE               = VAR_REGULAR;
    SET NEW.INSTALLMENT_PRICE           = VAR_INSTALLMENT;

    SET NEW.CURRENT_SS_COST             = VAR_SS_COST;
    SET NEW.CURRENT_SM_COST             = VAR_SM_COST;
    SET NEW.CURRENT_AIR_FREIGHT         = VAR_AIR_FREIGHT;
    SET NEW.CURRENT_SEA_FREIGHT         = VAR_SEA_FREIGHT;
    SET NEW.CURRENT_REGULAR_PRICE       = VAR_REGULAR;
    SET NEW.CURRENT_INSTALLMENT_PRICE   = VAR_INSTALLMENT;
    SET NEW.ORDER_STATUS                = 10;
    SET VAR_IS_REGULAR                  = NEW.CURRENT_IS_REGULAR;
    set NEW.F_SHIPPMENT_NO              = VAR_F_SHIPPMENT_NO;
    set NEW.F_INV_WAREHOUSE_NO          = VAR_F_INV_WAREHOUSE_NO;
    set NEW.F_BOX_NO                    = VAR_F_BOX_NO;


    IF VAR_IS_REGULAR = 0 THEN
        SET VAR_UNIT_PRICE = VAR_INSTALLMENT;
    ELSE
        SET VAR_UNIT_PRICE = VAR_REGULAR;
    END IF;

    SELECT AMOUNT INTO VAR_SINGLE_COMISSION FROM SLS_COMMISION WHERE VAR_UNIT_PRICE BETWEEN FROM_PRICE AND TO_PRICE;
    SET NEW.COMISSION = VAR_SINGLE_COMISSION;

    SELECT TOTAL_COMISSION INTO VAR_TOTAL_COMISSION FROM SLS_BOOKING WHERE PK_NO = NEW.F_BOOKING_NO;
    SET VAR_TOTAL_COMISSION = VAR_TOTAL_COMISSION + VAR_SINGLE_COMISSION;
    UPDATE SLS_BOOKING SET TOTAL_COMISSION = VAR_TOTAL_COMISSION WHERE PK_NO = NEW.F_BOOKING_NO;

    -- UPDATE LINE_PRICE
    IF NEW.CURRENT_IS_FREIGHT = 1 THEN
        SET VAR_TOTAL_LINE_VALUE = VAR_TOTAL_LINE_VALUE+NEW.CURRENT_AIR_FREIGHT;
        ELSEIF NEW.CURRENT_IS_FREIGHT = 2 THEN
        SET VAR_TOTAL_LINE_VALUE = VAR_TOTAL_LINE_VALUE+NEW.CURRENT_SEA_FREIGHT;
        ELSE
        SET VAR_TOTAL_LINE_VALUE = VAR_TOTAL_LINE_VALUE + 0;
        END IF;

        IF NEW.IS_SELF_PICKUP = 0 THEN
           IF NEW.CURRENT_IS_SM = 1 THEN
           SET VAR_TOTAL_LINE_VALUE = VAR_TOTAL_LINE_VALUE+NEW.CURRENT_SM_COST;
           ELSE
           SET VAR_TOTAL_LINE_VALUE = VAR_TOTAL_LINE_VALUE+NEW.CURRENT_SS_COST;
           END IF;  
        END IF;

        IF NEW.CURRENT_IS_REGULAR = 1 THEN
        SET VAR_TOTAL_LINE_VALUE = VAR_TOTAL_LINE_VALUE+NEW.CURRENT_REGULAR_PRICE;
        ELSE
        SET VAR_TOTAL_LINE_VALUE = VAR_TOTAL_LINE_VALUE+NEW.CURRENT_INSTALLMENT_PRICE;
        END IF;

        SET NEW.LINE_PRICE = VAR_TOTAL_LINE_VALUE;

END
/
