CREATE TRIGGER BEFORE_ACC_CUSTOMER_PAYMENTS_INSERT
  BEFORE INSERT
  ON ACC_CUSTOMER_PAYMENTS FOR EACH ROW
BEGIN
    declare VAR_NAME VARCHAR(200) default NULL;
    declare VAR_MOBILE_NO VARCHAR(200) default NULL;
    declare VAR_CUSTOMER_NO INT(11) default 0;
    declare VAR_CNAME VARCHAR(200) default NULL;

    declare VAR_PAYMENT_BANK_NAME VARCHAR(200) default NULL;
    declare VAR_PAYMENT_ACCOUNT_NAME VARCHAR(200) default NULL;
    declare VAR_BANK_ACC_NO VARCHAR(200) default NULL;


    declare VAR_TXN_REF VARCHAR(155) default NULL;
    declare VAR_TXN_DATE DATE default NULL;
    declare VAR_AMOUNT_ACTUAL Float default 0;
    declare VAR_F_PAYMENT_ACC_NO INT(11) default 0;
    declare VAR_F_CUSTOMER_NO INT(11) default 0;
    declare VAR_F_SHOP_NO INT(11) default 0;
    declare VAR_F_CUSTOMER_PAYMENT_NO INT(11) default 0;
    declare VAR_F_SS_CREATED_BY INT(11) default 0;
    declare VAR_PAYMENT_TYPE VARCHAR(100) default NULL;
    declare VAR_IS_COD INT(11) default 0;


    SELECT
        CUSTOMER_NO
        ,NAME
        ,MOBILE_NO
        INTO
        VAR_CUSTOMER_NO
        ,VAR_NAME
        ,VAR_MOBILE_NO
    FROM SLS_CUSTOMERS
    WHERE SLS_CUSTOMERS.PK_NO = NEW.F_CUSTOMER_NO
    ;

    SET NEW.CUSTOMER_NO = VAR_CUSTOMER_NO;
    SET NEW.CUSTOMER_NAME = VAR_NAME;
    SET NEW.CUSTOMER_MOBILE_NO = VAR_MOBILE_NO;

    SELECT
        NAME
        INTO
        VAR_CNAME
        FROM SS_CURRENCY
    WHERE SS_CURRENCY.PK_NO = NEW.F_PAYMENT_CURRENCY_NO;

    SET NEW.CURRENCY_NAME = VAR_CNAME;

    SELECT
        ACC_PAYMENT_BANK_ACC.BANK_NAME
        ,ACC_PAYMENT_BANK_ACC.BANK_ACC_NAME
        ,ACC_PAYMENT_BANK_ACC.BANK_ACC_NO
        INTO
        VAR_PAYMENT_BANK_NAME
        ,VAR_PAYMENT_ACCOUNT_NAME
        ,VAR_BANK_ACC_NO
        FROM ACC_PAYMENT_BANK_ACC
    WHERE ACC_PAYMENT_BANK_ACC.PK_NO = NEW.F_PAYMENT_ACC_NO
    ;

           SET NEW.PAYMENT_BANK_NAME =  VAR_PAYMENT_BANK_NAME;
    SET NEW.PAYMENT_ACCOUNT_NAME =  VAR_PAYMENT_ACCOUNT_NAME;
    SET NEW.PAYMENT_BANK_ACC_NO =  VAR_BANK_ACC_NO;

END
/


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
CREATE TRIGGER AFTER_ACC_CUSTOMER_PAYMENTS_INSERT
  AFTER INSERT
  ON ACC_CUSTOMER_PAYMENTS FOR EACH ROW
BEGIN


 INSERT INTO ACC_BANK_TXN
 (
    TXN_REF
    ,TXN_TYPE_IN_OUT
    ,TXN_DATE
    ,AMOUNT_ACTUAL
    ,IS_CUS_SELLER_BANK_RECONCILATION
    ,F_PAYMENT_ACC_NO
    ,F_CUSTOMER_NO
    ,F_SHOP_NO
    ,F_CUSTOMER_PAYMENT_NO
    ,F_SS_CREATED_BY
    ,SS_CREATED_ON
    ,IS_COD
    ,PAYMENT_TYPE
    )
 VALUES (
    NEW.SLIP_NUMBER
    ,'1'
    ,NEW.PAYMENT_DATE
    ,NEW.PAY_AMOUNT
    ,'1'
    , NEW.F_PAYMENT_ACC_NO
    ,NEW.F_CUSTOMER_NO
    ,NEW.F_SHOP_NO
    ,NEW.PK_NO
    ,NEW.F_SS_CREATED_BY
    ,NOW()
    ,NEW.IS_COD
    ,NEW.PAYMENT_TYPE
    );


END
/

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
CREATE TRIGGER AFTER_ACC_BANK_TXN_INSERT
  AFTER INSERT
  ON ACC_BANK_TXN FOR EACH ROW
BEGIN

DECLARE VAR_BALANCE_ACTUAL FLOAT default 0 ;


SELECT SUM(AMOUNT_ACTUAL) INTO VAR_BALANCE_ACTUAL FROM ACC_BANK_TXN WHERE F_PAYMENT_ACC_NO = NEW.F_PAYMENT_ACC_NO;
UPDATE ACC_PAYMENT_BANK_ACC SET BALANCE_ACTUAL = VAR_BALANCE_ACTUAL WHERE PK_NO = NEW.F_PAYMENT_ACC_NO;


END
