DROP TRIGGER IF EXISTS `BEFORE_SLS_BOOKING_INSERT`;

DELIMITER $$


CREATE TRIGGER `BEFORE_SLS_BOOKING_INSERT` BEFORE INSERT ON `SLS_BOOKING`
    FOR EACH ROW

  BEGIN
DECLARE VAR_BOOKING_NO INT(11) DEFAULT 0;

SELECT IFNULL(MAX(BOOKING_NO),60000) INTO VAR_BOOKING_NO
        FROM SLS_BOOKING;
        SET NEW.BOOKING_NO = VAR_BOOKING_NO+1 ;

END;
$$
