CREATE PROCEDURE PROC_CUSTOMER_BOOKING(
    IN_PK_NO Integer(11), 
    IN_POSTAGE_COST FLOAT,
    IN_COUPON_DISCOUNT FLOAT,
    IN_DISCOUNT FLOAT
    )
  NO SQL
    BEGIN

        DECLARE VAR_TOTAL_PRICE FLOAT default 0;
        DECLARE VAR_SUBTOTAL_PRICE FLOAT default 0;
        DECLARE VAR_POSTAGE_COST FLOAT default 0;
        DECLARE VAR_DISCOUNT FLOAT default 0;
        DECLARE VAR_COUPON_DISCOUNT FLOAT default 0;
        DECLARE VAR_TOTAL_PRICE_DECIMAL FLOAT default 0;
        DECLARE VAR_TOTAL_ITEM_QTY int default 0; 
        DECLARE VAR_SUBTOTAL_PRICE_DECIMAL FLOAT default 0;

        INSERT INTO A VALUES(2);


        SELECT SUM(LINE_QTY) AS TOTAL_QTY,SUM(LINE_PRICE) INTO VAR_TOTAL_ITEM_QTY,VAR_SUBTOTAL_PRICE

        FROM SLS_BOOKING_DETAILS

        WHERE F_BOOKING_NO = IN_PK_NO;

        INSERT INTO A VALUES(3);
        
        SELECT (VAR_SUBTOTAL_PRICE % 1) INTO VAR_SUBTOTAL_PRICE_DECIMAL;
        IF VAR_SUBTOTAL_PRICE_DECIMAL < .5 THEN
        SELECT FLOOR(VAR_SUBTOTAL_PRICE) INTO VAR_SUBTOTAL_PRICE;
        ELSE
        SELECT CEILING(VAR_SUBTOTAL_PRICE) INTO VAR_SUBTOTAL_PRICE;
        END IF;

        INSERT INTO A VALUES(4);


        UPDATE SLS_BOOKING SET 
        TOTAL_ITEM_QTY = VAR_TOTAL_ITEM_QTY,
        SUB_TOTAL = IFNULL(VAR_SUBTOTAL_PRICE,0),
        POSTAGE_COST = IFNULL(IN_POSTAGE_COST,0),
        COUPON_DISCOUNT = IFNULL(IN_COUPON_DISCOUNT,0),
        DISCOUNT = IFNULL(IN_DISCOUNT,0),
        TOTAL_PRICE = (IFNULL(VAR_SUBTOTAL_PRICE,0)+IFNULL(IN_POSTAGE_COST,0)) - (IFNULL(COUPON_DISCOUNT,0)+IFNULL(DISCOUNT,0))
        WHERE PK_NO = IN_PK_NO;
        INSERT INTO A VALUES(5);


END
/
